### ISSUE TITLE
memory.memsw.limit not set in cgroup (swap treated differently)

### ISSUE THREAD

**Issue by itkovian** [adaptivecomputing/torque#372]
Hi,

We see in the code that the mem_limit and the swap_limit are both set in a different way.

In `start_exec.c`:

~~~~{.c}
unsigned long long get_memory_limit_for_this_host(
  job          *pjob,
  complete_req *cr,
  std::string  &string_hostname)

  {
  unsigned long long mem_limit = 0;

  if (cr != NULL)
    mem_limit = cr->get_memory_for_this_host(string_hostname);

  if (mem_limit == 0)
    {
    mem_limit = get_memory_limit_from_resource_list(pjob);
    }

  return(mem_limit);
  } // END get_memory_limit_for_this_host()
~~~~

versus

~~~~{.c}
unsigned long long get_swap_limit_for_this_host(

  job          *pjob,
  complete_req *cr,
  std::string  &string_hostname)

  {
  unsigned long long swap_limit = 0;

  if (cr != NULL)
    swap_limit = cr->get_swap_memory_for_this_host(string_hostname);

  return(swap_limit);
  } // END get_swap_limit_for_this_host()
~~~~

So if cr is NULL we end up in a different path. We know for certain that at least for the mem_limit the path with get_memory_limit_from_resource_list is taken. 

As a result, we see the following in the cgroup (note that there is now a single cgroup (using `legacy_vmem = True` and `-l` options) of the job

~~~~
/sys/fs/cgroup/memory/torque/286.master23.banette.gent.vsc/memory.kmem.limit_in_bytes:9223372036854775807 
/sys/fs/cgroup/memory/torque/286.master23.banette.gent.vsc/memory.kmem.tcp.limit_in_bytes:9223372036854775807 
/sys/fs/cgroup/memory/torque/286.master23.banette.gent.vsc/memory.limit_in_bytes:1610612736 
/sys/fs/cgroup/memory/torque/286.master23.banette.gent.vsc/memory.memsw.limit_in_bytes:9223372036854775807 
/sys/fs/cgroup/memory/torque/286.master23.banette.gent.vsc/memory.soft_limit_in_bytes:9223372036854775807 
~~~~

qstat -f states:

~~~~
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 3gb
    Resource_List.walltime = 00:10:00
~~~~

- branch 6.0-dev
- commit 5e082b7

Kind regards,
-- Andy

**Comment by knielson** [comment]
Memory and swap are set differently.
cgroups will not allow swap to be set if memory is not set so we must set a memory value.

We have also fixed bugs for vmem the latest being commit 09c616b3a6abdaad32716598453cbf027e966f06.

You may want to download the latest 6.0-dev and see if this problem has been taken care of.

**Comment by itkovian** [comment]
I do not think it's fixed. Used 0f986da, but I still see

~~~~
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.kmem.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.kmem.tcp.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.limit_in_bytes:1610612736
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.memsw.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.soft_limit_in_bytes:9223372036854775807
~~~~

for a job submitted with

~~~~~
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 3gb
    Resource_List.walltime = 00:10:00
~~~~

**Comment by itkovian** [comment]
Can you guys actually reproduce our issue?

**Comment by knielson** [comment]
Andy,

Yes. I will have a fix today.

Ken

On Mon, Jun 20, 2016 at 7:26 AM, Andy Georges <notifications@github.com>
wrote:

> Can you guys actually reproduce our issue?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/372#issuecomment-227141204>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACCEHDe0wVi7qlFnZJ5ji6pr9XRxdQzdks5qNpT3gaJpZM4IyA0N>
> .
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by knielson** [comment]
Andy,

Here is the latest commit. 
e9252c1..30fc3cc 6.0-dev -> 6.0-dev
7aacdf9..efc72e3 develop -> develop

If we are not all the way there yet we should at least be closer. Let me know what you find.

Ken

**Comment by itkovian** [comment]
Hi,

I am running 6.0-dev, commit 332175e.

I see the following:

~~~~
/sys/fs/cgroup/memory/torque/353.master23.banette.gent.vsc/memory.kmem.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/353.master23.banette.gent.vsc/memory.kmem.tcp.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/353.master23.banette.gent.vsc/memory.limit_in_bytes:1610612736
/sys/fs/cgroup/memory/torque/353.master23.banette.gent.vsc/memory.memsw.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/353.master23.banette.gent.vsc/memory.soft_limit_in_bytes:9223372036854775807
~~~~

~~~~
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 3gb
    Resource_List.walltime = 00:10:00
~~~~

**Comment by itkovian** [comment]
Did it actually work on your end?

**Comment by knielson** [comment]
Andy,

Yes. It is working here.

We do not set kmem.

I'm not sure why swap is not working for you. Is it possible to get on your
system to debug

**Comment by itkovian** [comment]
Yes, there is a public key for Wil and Rick on the test system, which they can use to get there.

**Comment by itkovian** [comment]
I just submitted an interactive job

~~~~
vsc40075@node2803 (banette) ~/vsc-testing/torque> qsub -I -l walltime=2:00:00:00 -l nodes=1:ppn=2 -l vmem=3g
qsub: waiting for job 354.master23.banette.gent.vsc to start
qsub: job 354.master23.banette.gent.vsc ready
~~~~


qstat -f output

~~~~
Job Id: 355.master23.banette.gent.vsc
    Job_Name = STDIN
    Job_Owner = vsc40075@node2803.banette.gent.vsc
    job_state = R
    queue = long
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Tue Jun 21 16:29:49 2016
    Error_Path = /dev/pts/0
    exec_host = node2801.banette.gent.vsc/0-1+node2802.banette.gent.vsc/0-1
    Hold_Types = n
    interactive = True
    Join_Path = n
    Keep_Files = n
    Mail_Points = n
    mtime = Tue Jun 21 16:29:59 2016
    Output_Path = /dev/pts/0
    Priority = 0
    qtime = Tue Jun 21 16:29:49 2016
    Rerunable = False
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 3gb
    Resource_List.walltime = 48:00:00
    session_id = 2340
    Variable_List = PBS_O_QUEUE=default,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,
	PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/v
	sc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/loc
	al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin,
	PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vs
	c-testing/torque,PBS_O_HOST=node2803.banette.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40075
    egroup = vsc40075
    queue_type = E
    etime = Tue Jun 21 16:29:49 2016
    submit_args = -I -l walltime=2:00:00:00 -l nodes=2:ppn=2 -l vmem=3g
    start_time = Tue Jun 21 16:29:59 2016
    Walltime.Remaining = 172758
    start_count = 1
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = node2803.banette.gent.vsc
    request_version = 1
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.memory.0 = 3145728kb
    req_information.swap.0 = 3145728kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
    req_information.hostlist.0 = node2802.banette.gent.vsc:ppn=2
    req_information.task_usage.0.task.0.cpu_list = 0-1
    req_information.task_usage.0.task.0.mem_list = 0
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 2
    req_information.task_usage.0.task.0.host = node2801.banette.gent.vsc
    req_information.task_usage.0.task.1.cpu_list = 0-1
    req_information.task_usage.0.task.1.mem_list = 0
    req_information.task_usage.0.task.1.cores = 0
    req_information.task_usage.0.task.1.threads = 2
    req_information.task_usage.0.task.1.host = node2802.banette.gent.vsc
    cpuset_string = node2801.banette.gent.vsc:0-1+node2802.banette.gent.vsc:0-
	1
    memset_string = node2801.banette.gent.vsc:0+node2802.banette.gent.vsc:0
~~~~

cgroup settings

~~~~
vsc40075@node2801 (banette) ~> cat /sys/fs/cgroup/memory/torque/355.master23.banette.gent.vsc/memory.limit_in_bytes
1610612736
vsc40075@node2801 (banette) ~> cat /sys/fs/cgroup/memory/torque/355.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
9223372036854775807
vsc40075@node2801 (banette) ~> ls /sys/fs/cgroup/memory/torque/355.master23.banette.gent.vsc/
cgroup.clone_children		memory.kmem.tcp.max_usage_in_bytes  memory.oom_control
cgroup.event_control		memory.kmem.tcp.usage_in_bytes	    memory.pressure_level
cgroup.procs			memory.kmem.usage_in_bytes	    memory.soft_limit_in_bytes
memory.failcnt			memory.limit_in_bytes		    memory.stat
memory.force_empty		memory.max_usage_in_bytes	    memory.swappiness
memory.kmem.failcnt		memory.memsw.failcnt		    memory.usage_in_bytes
memory.kmem.limit_in_bytes	memory.memsw.limit_in_bytes	    memory.use_hierarchy
memory.kmem.max_usage_in_bytes	memory.memsw.max_usage_in_bytes     notify_on_release
memory.kmem.slabinfo		memory.memsw.usage_in_bytes	    tasks
memory.kmem.tcp.failcnt		memory.move_charge_at_immigrate
memory.kmem.tcp.limit_in_bytes	memory.numa_stat
vsc40075@node2801 (banette) ~> cat /sys/fs/cgroup/memory/torque/355.master23.banette.gent.vsc/tasks
2340
2341
2449
2450
2747
~~~~

**Comment by itkovian** [comment]
Submitting a single node job, with two cores seems to work for the memory limit, at least:

~~~~
vsc40075@node2803 (banette) ~/vsc-testing/torque> qsub -I -l walltime=2:00:00:00 -l nodes=1:ppn=2 -l vmem=3g
qsub: waiting for job 356.master23.banette.gent.vsc to start
qsub: job 356.master23.banette.gent.vsc ready
~~~~

qstat -f output

~~~~
vsc40075@node2801 (banette) ~> qstat -f
Job Id: 356.master23.banette.gent.vsc
    Job_Name = STDIN
    Job_Owner = vsc40075@node2803.banette.gent.vsc
    job_state = R
    queue = long
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Tue Jun 21 16:45:12 2016
    Error_Path = node2803.banette.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gen
	t/vsc400/vsc40075/vsc-testing/torque/STDIN.e356
    exec_host = node2801.banette.gent.vsc/0-1
    Hold_Types = n
    interactive = True
    Join_Path = n
    Keep_Files = n
    Mail_Points = n
    mtime = Tue Jun 21 16:45:24 2016
    Output_Path = node2803.banette.gent.vsc:/vscmnt/gent_vulpix/_/user/home/ge
	nt/vsc400/vsc40075/vsc-testing/torque/STDIN.o356
    Priority = 0
    qtime = Tue Jun 21 16:45:12 2016
    Rerunable = False
    Resource_List.nice = 0
    Resource_List.nodect = 1
    Resource_List.nodes = 1:ppn=2
    Resource_List.vmem = 3gb
    Resource_List.walltime = 48:00:00
    session_id = 3354
    Variable_List = PBS_O_QUEUE=default,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,
	PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/v
	sc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/loc
	al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin,
	PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vs
	c-testing/torque,PBS_O_HOST=node2803.banette.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40075
    egroup = vsc40075
    queue_type = E
    etime = Tue Jun 21 16:45:12 2016
    submit_args = -I -l walltime=2:00:00:00 -l nodes=1:ppn=2 -l vmem=3g
    start_time = Tue Jun 21 16:45:24 2016
    Walltime.Remaining = 172795
    start_count = 1
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = node2803.banette.gent.vsc
    request_version = 1
    req_information.task_count.0 = 1
    req_information.lprocs.0 = 2
    req_information.memory.0 = 3145728kb
    req_information.swap.0 = 3145728kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
    req_information.task_usage.0.task.0.cpu_list = 0-1
    req_information.task_usage.0.task.0.mem_list = 0
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 2
    req_information.task_usage.0.task.0.host = node2801.banette.gent.vsc
    cpuset_string = node2801.banette.gent.vsc:0-1
    memset_string = node2801.banette.gent.vsc:0
~~~~

~~~~
vsc40075@node2801 (banette) ~>  cat /sys/fs/cgroup/memory/torque/356.master23.banette.gent.vsc/memory.limit_in_bytes
3221225472
vsc40075@node2801 (banette) ~>  cat /sys/fs/cgroup/memory/torque/356.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
9223372036854775807
vsc40075@node2801 (banette) ~> ls /sys/fs/cgroup/memory/torque/356.master23.banette.gent.vsc/
cgroup.clone_children		memory.kmem.tcp.max_usage_in_bytes  memory.oom_control
cgroup.event_control		memory.kmem.tcp.usage_in_bytes	    memory.pressure_level
cgroup.procs			memory.kmem.usage_in_bytes	    memory.soft_limit_in_bytes
memory.failcnt			memory.limit_in_bytes		    memory.stat
memory.force_empty		memory.max_usage_in_bytes	    memory.swappiness
memory.kmem.failcnt		memory.memsw.failcnt		    memory.usage_in_bytes
memory.kmem.limit_in_bytes	memory.memsw.limit_in_bytes	    memory.use_hierarchy
memory.kmem.max_usage_in_bytes	memory.memsw.max_usage_in_bytes     notify_on_release
memory.kmem.slabinfo		memory.memsw.usage_in_bytes	    tasks
memory.kmem.tcp.failcnt		memory.move_charge_at_immigrate
memory.kmem.tcp.limit_in_bytes	memory.numa_stat
vsc40075@node2801 (banette) ~> cat /sys/fs/cgroup/memory/torque/356.master23.banette.gent.vsc/tasks
3354
3355
3445
3595
~~~~

But not for the memsw limit.

**Comment by knielson** [comment]
Thanks. I will talk to Rick

**Comment by itkovian** [comment]
Would it be possible to submit the same test job we use, to make sure we're effectively looking at the same thing?

job script:
~~~~{.bash}
#!/bin/bash

#PBS -l nodes=2:ppn=1
#PBS -l walltime=00:10:00
#PBS -l vmem=2gb

# this script will compile the allocation test code and
# attempt to allocate 2GiB, which will fail when asking
# 2 GiB vmem across 2 nodes with legacy_vmem disabled and
# which should work when legacy_vmem is enabled


unique_nodecount=$(pbsdsh -o hostname | sort |uniq |wc -l)

if [ "$unique_nodecount" -ne 2 ]; then
    echo "Not running on 2 distinct nodes, bailing (unique_nodecount: $unique_nodecount)"
    exit 1
fi;

cd "$PBS_O_WORKDIR" || exit 1

pbsdsh -o $PWD/grep_cgroup_info.sh
~~~~

grep_cgroup_info.sh:

~~~~{.bash}
#!/bin/bash

#
# Copyright 2016-2016 Ghent University
#
# This file is part of vsc-testing,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# the Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# https://github.com/hpcugent/vsc-testing
#
# vsc-testing is free software: you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as
# published by the Free Software Foundation, either version 2 of
# the License, or (at your option) any later version.
#
# vsc-testing is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with vsc-testing If not, see <http://www.gnu.org/licenses/>.
#

function count_and_display() {
    # counts the number of different values we find in the output (residing in the $file)
    # for the given $string. It is expected that the value is the second field, the $string
    # can be found in the first field along with the $job_id

    file=$1
    string=$2
    expected_count=$3
    job_id=$4

    count=$(grep "${job_id}.*${string}" < ${file} | cut -d":" -f2 | sort -u | wc -l)

    if [ $count -eq 1 ]; then
        echo -n "${string}: "
        grep "${job_id}.*${string}" < ${file} | cut -d":" -f2 | sort -u
    else
        echo -n "${string}:${count}:"
        grep "${job_id}.*${string}" < ${file} | sort -u | tr "\n" "," | sed 's/,$//'
        echo
    fi
}

# Work on EL6 and EL7 machines
if [ -d /cgroup ]; then
   base="/cgroup"
else
   base="/sys/fs/cgroup"
fi

# get basic information about the job's environment
uname -a
rpm -q torque
env | sort
echo "\$\$: $$"
cat /proc/self/cgroup

# determine the output file for this job's cgroup information
outfile="$PBS_O_WORKDIR/${PBS_JOBID}_task_${PBS_TASKNUM}_cgroups.out"
echo "output file for cgroups data: $outfile"

targets="(tasks|limit_in_bytes)"
grep -r '' $base/memory/torque/$PBS_JOBID/* 2>/dev/null | egrep -e "$targets" > $outfile

# summarise information found in the output
count_and_display ${outfile} "memory.limit_in_bytes" 1 $PBS_JOBID
count_and_display ${outfile} "memory.memsw.limit_in_bytes" 1 $PBS_JOBID

# get requested job resources
qstat -f1 $PBS_JOBID | egrep -e "(Resource|req_information)"
~~~~

**Comment by itkovian** [comment]
OK, so to update this with the info we got from the debugging session.

- the complete_req structure is not used because we were looking at the wrong hostname
- this means that swap is not getting set, but memory is, since there's another way to retrieve the information that is only used for mem_limit (see the original issue statement)
- unclear if this means the legacy_vmem issue will be solved (to be tested :)

**Comment by itkovian** [comment]
With #378, I think some of the issues are resolved. In any case, I now get correct memory.limit_in_bytes and memory.memsw.limit_in_bytes -- at least for a vmem request that is smaller than the amount of RAM in the node:

~~~~
memory.limit_in_bytes: 3221225472
memory.memsw.limit_in_bytes: 3221225472
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 3gb
    Resource_List.walltime = 00:30:00
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.memory.0 = 3145728kb
    req_information.swap.0 = 3145728kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
    req_information.hostlist.0 = node2802.banette.gent.vsc:ppn=2
    req_information.task_usage.0.task.0.cpu_list = 0-1
    req_information.task_usage.0.task.0.mem_list = 0
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 2
    req_information.task_usage.0.task.0.host = node2801.banette.gent.vsc
    req_information.task_usage.0.task.1.cpu_list = 0-1
    req_information.task_usage.0.task.1.mem_list = 0
    req_information.task_usage.0.task.1.cores = 0
    req_information.task_usage.0.task.1.threads = 2
    req_information.task_usage.0.task.1.host = node2802.banette.gent.vsc
~~~~

**Comment by itkovian** [comment]
I can confirm that under 56698fb, this is resolved as well. Both memory.limit_in_bytes and memory.memsw.limit_in_bytes are set correctly:

~~~~
memory.limit_in_bytes: 4144447488
memory.memsw.limit_in_bytes: 8589934592
~~~~

~~~~
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 8gb
    Resource_List.walltime = 00:30:00
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.swap.0 = 8388608kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
    req_information.hostlist.0 = node2802.banette.gent.vsc:ppn=2
    req_information.task_usage.0.task.0.cpu_list = 0-1
    req_information.task_usage.0.task.0.mem_list = 0
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 2
    req_information.task_usage.0.task.0.host = node2801.banette.gent.vsc
    req_information.task_usage.0.task.1.cpu_list = 0-1
    req_information.task_usage.0.task.1.mem_list = 0
    req_information.task_usage.0.task.1.cores = 0
    req_information.task_usage.0.task.1.threads = 2
    req_information.task_usage.0.task.1.host = node2802.banette.gent.vsc
~~~~

Nodes have ~ 3.8G physical memory, so the above values make sense and the swap limit is set correctly.

**Comment by itkovian** [comment]
@knielson I now do observe the following (56698fb):

~~~~
[root@master23 ~]# qstat -n

master23.banette.gent.vsc:
                                                                                  Req'd       Req'd       Elap
Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory      Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ --------- --------- - ---------
426.master23.banette.g  vsc40075    short    test_cgroups_tas      0     2      2       7gb  00:30:00 R  00:00:01
   node2801+node2802
427.master23.banette.g  vsc40075    short    test_cgroups_tas      0     2      2       7gb  00:30:00 R  00:00:01
   node2801+node2802
[root@master23 ~]# pbsmon
 2801 2802 2803 2804 2805
    J    J    .    .    .

 2806 2807 2808
    .    .    .

   J full                 : 2   |   . offline              : 6   |
   j partial              : 0   |   X down                 : 0   |
   _ free                 : 0   |   x down_on_error        : 0   |
                                |   o other                : 0   |

Node type:
 ppn=2, physmem=3.8GB, swap=8.0GB, vmem=11.8GB, local disk=10.5GB
~~~~

two jobs, requesting vmem=7g, are both running on the nodes, so their request sum exceeds the total available mem+swap.

The cgroup limits are set as follows:

~~~~
[root@node2801 torque]# cat 426.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
7516192768
[root@node2801 torque]# cat 427.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
7516192768
[root@node2801 torque]# cat 426.master23.banette.gent.vsc/memory.limit_in_bytes
4144447488
[root@node2801 torque]# cat 427.master23.banette.gent.vsc/memory.limit_in_bytes
4144447488
~~~~

So, this is in line with the expected values, but imho the second job should never have started. Or am I missing something here?

**Comment by itkovian** [comment]
If I start each job requesting `vmem=10g`, I see

~~~~
[root@master23 ~]# mdiag -n -vv
compute node summary
Name                    State   Procs      Memory         Disk          Swap      Speed   Opsys   Arch Par   Load Classes                        Features

node2801.banette.gent.vsc  Running    0:2      3952:3952    10913:10955    1689:12144   1.00   linux      - ban   2.03 [bshort][debug][short][long][q72h][special][workshop][q1h][q24h] hadoop,collectl,ecryptid1,ecryptid2,ecryptid3  GRES=socket:1,numanode:1,core:2,thread:2 NODEINDEX=2801
node2802.banette.gent.vsc  Running    0:2      3952:3952    10915:10955    1714:12144   1.00   linux      - ban   2.01 [bshort][debug][short][long][q72h][special][workshop][q1h][q24h] hadoop,collectl,ecryptid1,ecryptid2,ecryptid3  GRES=socket:1,numanode:1,core:2,thread:2 NODEINDEX=2802
<snip>
~~~~

So it'd certainly strange that moab thinks there's still e.g. `1689:12144` m free if there are two jobs each requesting 10g. 

Could it be that you're not tracking the correct information server side as well, again diving the 'allocated' vmem by the nodecount as if legacy_vmem was False?

**Comment by itkovian** [comment]
If I only request a single node, single core, the second job will _not_ start, as expected.

**Comment by knielson** [comment]
What does mdiag -n show for memory on the node?

Ken

On Fri, Jul 1, 2016 at 3:36 AM, Andy Georges <notifications@github.com>
wrote:

> @knielson <https://github.com/knielson> I now do observe the following (
> 56698fb
> <https://github.com/adaptivecomputing/torque/commit/56698fbe7f500208cac636668bd6fa75887e886f>
> ):
>
> [root@master23 ~]# qstat -n
>
> master23.banette.gent.vsc:
>                                                                                   Req'd       Req'd       Elap
> Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory      Time    S   Time
> ----------------------- ----------- -------- ---------------- ------ ----- ------ --------- --------- - ---------
> 426.master23.banette.g  vsc40075    short    test_cgroups_tas      0     2      2       7gb  00:30:00 R  00:00:01
>    node2801+node2802
> 427.master23.banette.g  vsc40075    short    test_cgroups_tas      0     2      2       7gb  00:30:00 R  00:00:01
>    node2801+node2802
> [root@master23 ~]# pbsmon
>  2801 2802 2803 2804 2805
>     J    J    .    .    .
>
>  2806 2807 2808
>     .    .    .
>
>    J full                 : 2   |   . offline              : 6   |
>    j partial              : 0   |   X down                 : 0   |
>    _ free                 : 0   |   x down_on_error        : 0   |
>                                 |   o other                : 0   |
>
> Node type:
>  ppn=2, physmem=3.8GB, swap=8.0GB, vmem=11.8GB, local disk=10.5GB
>
> two jobs, requesting vmem=7g, are both running on the nodes, so their
> request sum exceeds the total available mem+swap.
>
> The cgroup limits are set as follows:
>
> [root@node2801 torque]# cat 426.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
> 7516192768
> [root@node2801 torque]# cat 427.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
> 7516192768
> [root@node2801 torque]# cat 426.master23.banette.gent.vsc/memory.limit_in_bytes4144447488
> [root@node2801 torque]# cat 427.master23.banette.gent.vsc/memory.limit_in_bytes4144447488
>
> So, this is in line with the expected values, but imho the second job
> should never have started. Or am I missing something here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/372#issuecomment-229903412>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACCEHID2AsgPFCuFPBYUdDC0Eg6OwTyUks5qRN-lgaJpZM4IyA0N>
> .
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by knielson** [comment]
Scratch that last request. I should have read the next e-mail

On Fri, Jul 1, 2016 at 8:31 AM, Ken Nielson <knielson@adaptivecomputing.com>
wrote:

> What does mdiag -n show for memory on the node?
>
> Ken
>
> On Fri, Jul 1, 2016 at 3:36 AM, Andy Georges <notifications@github.com>
> wrote:
>
>> @knielson <https://github.com/knielson> I now do observe the following (
>> 56698fb
>> <https://github.com/adaptivecomputing/torque/commit/56698fbe7f500208cac636668bd6fa75887e886f>
>> ):
>>
>> [root@master23 ~]# qstat -n
>>
>> master23.banette.gent.vsc:
>>                                                                                   Req'd       Req'd       Elap
>> Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory      Time    S   Time
>> ----------------------- ----------- -------- ---------------- ------ ----- ------ --------- --------- - ---------
>> 426.master23.banette.g  vsc40075    short    test_cgroups_tas      0     2      2       7gb  00:30:00 R  00:00:01
>>    node2801+node2802
>> 427.master23.banette.g  vsc40075    short    test_cgroups_tas      0     2      2       7gb  00:30:00 R  00:00:01
>>    node2801+node2802
>> [root@master23 ~]# pbsmon
>>  2801 2802 2803 2804 2805
>>     J    J    .    .    .
>>
>>  2806 2807 2808
>>     .    .    .
>>
>>    J full                 : 2   |   . offline              : 6   |
>>    j partial              : 0   |   X down                 : 0   |
>>    _ free                 : 0   |   x down_on_error        : 0   |
>>                                 |   o other                : 0   |
>>
>> Node type:
>>  ppn=2, physmem=3.8GB, swap=8.0GB, vmem=11.8GB, local disk=10.5GB
>>
>> two jobs, requesting vmem=7g, are both running on the nodes, so their
>> request sum exceeds the total available mem+swap.
>>
>> The cgroup limits are set as follows:
>>
>> [root@node2801 torque]# cat 426.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
>> 7516192768
>> [root@node2801 torque]# cat 427.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
>> 7516192768
>> [root@node2801 torque]# cat 426.master23.banette.gent.vsc/memory.limit_in_bytes4144447488
>> [root@node2801 torque]# cat 427.master23.banette.gent.vsc/memory.limit_in_bytes4144447488
>>
>> So, this is in line with the expected values, but imho the second job
>> should never have started. Or am I missing something here?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/adaptivecomputing/torque/issues/372#issuecomment-229903412>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ACCEHID2AsgPFCuFPBYUdDC0Eg6OwTyUks5qRN-lgaJpZM4IyA0N>
>> .
>>
>
>
>
> --
> [image: Adaptive Computing] <http://www.adaptivecomputing.com>
> [image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
> <http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits> [image:
> YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
> <https://plus.google.com/u/0/102155039310685515037/posts> [image:
> Facebook]
> <http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts> [image:
> RSS] <http://www.adaptivecomputing.com/feed>
> Ken Nielson Sr. Software Engineer
> +1 801.717.3700 office    +1 801.717.3738 fax
> 1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
> www.adaptivecomputing.com
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by knielson** [comment]
What does pbsnodes report for the node in the status line?

On Fri, Jul 1, 2016 at 7:12 AM, Andy Georges <notifications@github.com>
wrote:

> If I start each job requesting vmem=10g, I see
>
> [root@master23 ~]# mdiag -n -vv
> compute node summary
> Name                    State   Procs      Memory         Disk          Swap      Speed   Opsys   Arch Par   Load Classes                        Features
>
> node2801.banette.gent.vsc  Running    0:2      3952:3952    10913:10955    1689:12144   1.00   linux      - ban   2.03 [bshort][debug][short][long][q72h][special][workshop][q1h][q24h] hadoop,collectl,ecryptid1,ecryptid2,ecryptid3  GRES=socket:1,numanode:1,core:2,thread:2 NODEINDEX=2801
> node2802.banette.gent.vsc  Running    0:2      3952:3952    10915:10955    1714:12144   1.00   linux      - ban   2.01 [bshort][debug][short][long][q72h][special][workshop][q1h][q24h] hadoop,collectl,ecryptid1,ecryptid2,ecryptid3  GRES=socket:1,numanode:1,core:2,thread:2 NODEINDEX=2802
> <snip>
>
> So it'd certainly strange that moab thinks there's still e.g. 1689:12144
> m free if there are two jobs each requesting 10g.
>
> Could it be that you're not tracking the correct information server side
> as well, again diving the 'allocated' vmem by the nodecount as if
> legacy_vmem was False?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/adaptivecomputing/torque/issues/372#issuecomment-229942848>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACCEHGM_TrPOYlQwngp3_HLC1VtiWhZBks5qRRI3gaJpZM4IyA0N>
> .
>



-- 
[image: Adaptive Computing] <http://www.adaptivecomputing.com>
[image: Twitter] <http://twitter.com/AdaptiveMoab> [image: LinkedIn]
<http://www.linkedin.com/company/448673?goback=.fcs_GLHD_adaptive+computing_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits>
[image:
YouTube] <http://www.youtube.com/adaptivecomputing> [image: GooglePlus]
<https://plus.google.com/u/0/102155039310685515037/posts> [image: Facebook]
<http://www.facebook.com/pages/Adaptive-Computing/314449798572695?fref=ts>
[image:
RSS] <http://www.adaptivecomputing.com/feed>
Ken Nielson Sr. Software Engineer
+1 801.717.3700 office    +1 801.717.3738 fax
1712 S. East Bay Blvd, Suite 300     Provo, UT 84606
www.adaptivecomputing.com

**Comment by itkovian** [comment]
For node2801 and node2802
~~~~
[root@master23 ~]# pbsnodes node2801.banette.gent.vsc node2802.banette.gent.vsc
node2801.banette.gent.vsc
     state = free
     power_state = Running
     np = 2
     properties = hadoop,collectl,ecryptid1,ecryptid2,ecryptid3
     ntype = cluster
     status = rectime=1467397977,macaddr=aa:01:00:80:0a:01,cpuclock=Fixed,varattr=,jobs=,state=free,size=11175056kb:11218120kb,netload=190327079208,gres=,loadave=0.01,ncpus=2,physmem=4047312kb,availmem=12224780kb,totmem=12435916kb,idletime=377913,nusers=2,nsessions=2,sessions=986 11675,uname=Linux node2801.banette.os 3.10.0-327.4.5.el7.ug.1.x86_64 #1 SMP Wed Jan 27 11:28:29 CET 2016 x86_64,opsys=linux
     mom_service_port = 15002
     mom_manager_port = 15003
     total_sockets = 1
     total_numa_nodes = 1
     total_cores = 2
     total_threads = 2
     dedicated_sockets = 0
     dedicated_numa_nodes = 0
     dedicated_cores = 0
     dedicated_threads = 0

node2802.banette.gent.vsc
     state = free
     power_state = Running
     np = 2
     properties = hadoop,collectl,ecryptid1,ecryptid2,ecryptid3
     ntype = cluster
     status = rectime=1467397975,macaddr=aa:01:00:80:0a:03,cpuclock=Fixed,varattr=,jobs=,state=free,size=11177108kb:11218120kb,netload=1799488408,gres=,loadave=0.25,ncpus=2,physmem=4047312kb,availmem=12252444kb,totmem=12435916kb,idletime=121829,nusers=1,nsessions=1,sessions=20357,uname=Linux node2802.banette.os 3.10.0-327.4.5.el7.ug.1.x86_64 #1 SMP Wed Jan 27 11:28:29 CET 2016 x86_64,opsys=linux
     mom_service_port = 15002
     mom_manager_port = 15003
     total_sockets = 1
     total_numa_nodes = 1
     total_cores = 2
     total_threads = 2
     dedicated_sockets = 0
     dedicated_numa_nodes = 0
     dedicated_cores = 0
     dedicated_threads = 0
~~~~

**Comment by itkovian** [comment]
I am going to close this and follow up the other issues elsewhere. But it would seem that the last thing I mentioned is expected behaviour. Thanks.
