### ISSUE TITLE
Wrong resources specified in the job

### ISSUE THREAD

**Issue by itkovian** [adaptivecomputing/torque#373]
Hi,

When submitting a job with more vmem (legacy_vmem = True) than available physical memory, the job will not start.

Submission command:
~~~~
vsc40075@gligar03 (banette) ~/vsc-testing/torque> qsub -l nodes=2:ppn=2 -l walltime=1:00:00 -I
~~~~

Job file
~~~~
<?xml version="1.0"?>
<job>
  <version>131842</version>
  <state>1</state>
  <substate>10</substate>
  <server_flags>1</server_flags>
  <start_time>0</start_time>
  <jobid>303.master23.banette.gent.vsc</jobid>
  <fileprefix>303.master23.banette.gent.vsc</fileprefix>
  <queue>short</queue>
  <destination_queue>short</destination_queue>
  <record_type>1</record_type>
  <mom_address>0</mom_address>
  <mom_port>14</mom_port>
  <mom_rmport>0</mom_rmport>
  <attributes>
    <Job_Name flags="1">STDIN</Job_Name>
    <Job_Owner flags="1">vsc40075@gligar03.gligar.gent.vsc</Job_Owner>
    <job_state flags="1">Q</job_state>
    <queue flags="1">short</queue>
    <server flags="1">master23.banette.gent.vsc</server>
    <Checkpoint flags="1">u</Checkpoint>
    <ctime flags="1">1465481849</ctime>
    <Error_Path flags="1">gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vsc-testing/torque/STDIN.e303</Error_Path>
    <Hold_Types flags="1">0</Hold_Types>
    <interactive flags="1">44268</interactive>
    <Join_Path flags="1">n</Join_Path>
    <Keep_Files flags="1">n</Keep_Files>
    <Mail_Points flags="1">n</Mail_Points>
    <mtime flags="1">1465481849</mtime>
    <Output_Path flags="1">gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vsc-testing/torque/STDIN.o303</Output_Path>
    <Priority flags="1">0</Priority>
    <qtime flags="1">1465481849</qtime>
    <Rerunable flags="1">0</Rerunable>
    <Resource_List>
      <neednodes flags="1">2:ppn=2</neednodes>
      <nodect flags="1">2</nodect>
      <nodes flags="1">2:ppn=2</nodes>
      <vmem flags="1">8449062912b</vmem>
      <walltime flags="1">01:00:00</walltime>
    </Resource_List>
    <substate flags="1">10</substate>
    <Variable_List flags="1">PBS_O_QUEUE=default,PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/vsc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin,PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vsc-testing/torque,PBS_O_HOST=gligar03.gligar.gent.vsc,PBS_O_SERVER=master23.banette.gent.vsc</Variable_List>
    <euser flags="1">vsc40075</euser>
    <egroup flags="5">vsc40075</egroup>
    <hop_count flags="1">1</hop_count>
    <queue_rank flags="1">4</queue_rank>
    <queue_type flags="1">E</queue_type>
    <etime flags="1">1465481849</etime>
    <submit_args flags="1">-l nodes=2:ppn=2 -l walltime=1:00:00 -I</submit_args>
    <checkpoint_dir flags="1">/export/home/checkpoints</checkpoint_dir>
    <fault_tolerant flags="1">0</fault_tolerant>
    <job_radix flags="1">0</job_radix>
    <submit_host flags="1">gligar03.gligar.gent.vsc</submit_host>
    <request_version flags="1">1</request_version>
  </attributes>
</job>
~~~~

trace job output:
~~~~
/var/spool/pbs/mom_logs/20160609: No such file or directory
/var/spool/pbs/sched_logs/20160609: No such file or directory

Job: 302.master23.banette.gent.vsc

06/09/2016 16:11:53.724 S    enqueuing into default, state 1 hop 1
06/09/2016 16:11:53.726 S    dequeuing from default, state QUEUED
06/09/2016 16:11:53.726 S    enqueuing into short, state 1 hop 1
06/09/2016 16:11:53  A    queue=default
06/09/2016 16:11:53  A    queue=short
06/09/2016 16:12:03.303 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/09/2016 16:12:34.026 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/09/2016 16:12:34.027 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/09/2016 16:13:05.071 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/09/2016 16:13:05.072 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/09/2016 16:13:36.112 S    Job deleted at request of root@master23.banette.gent.vsc
06/09/2016 16:13:36.112 S    Not sending email: job requested no e-mail
06/09/2016 16:13:36.211 S    on_job_exit valid pjob: 302.master23.banette.gent.vsc (substate=59)
06/09/2016 16:13:36.212 S    dequeuing from short, state COMPLETE
06/09/2016 16:13:36  A    requestor=root@master23.banette.gent.vsc
~~~~

~~~~~
[root@master23 ~]# qstat -f 302
Job Id: 302.master23.banette.gent.vsc
    Job_Name = STDIN
    Job_Owner = vsc40075@gligar03.gligar.gent.vsc
    job_state = Q
    queue = short
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Thu Jun  9 16:11:53 2016
    Error_Path = gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gent
	/vsc400/vsc40075/vsc-testing/torque/STDIN.e302
    Hold_Types = n
    interactive = True
    Join_Path = n
    Keep_Files = n
    Mail_Points = n
    mtime = Thu Jun  9 16:11:53 2016
    Output_Path = gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gen
	t/vsc400/vsc40075/vsc-testing/torque/STDIN.o302
    Priority = 0
    qtime = Thu Jun  9 16:11:53 2016
    Rerunable = False
    Resource_List.neednodes = 2:ppn=2
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 8449062912b
    Resource_List.walltime = 01:00:00
    substate = 10
    Variable_List = PBS_O_QUEUE=default,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,
	PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/v
	sc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/loc
	al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin,
	PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vs
	c-testing/torque,PBS_O_HOST=gligar03.gligar.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40075
    egroup = vsc40075
    queue_rank = 2
    queue_type = E
    etime = Thu Jun  9 16:11:53 2016
    submit_args = -l nodes=2:ppn=2 -l walltime=1:00:00 -I
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = gligar03.gligar.gent.vsc
    request_version = 1
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.memory.0 = 8251038kb
    req_information.swap.0 = 8251038kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
~~~~

The node has 3.8GiB RAM, as can be seen in the pbsnodes output:
~~~~
[root@master23 ~]# pbsnodes node2801.banette.gent.vsc
node2801.banette.gent.vsc
     state = free
     power_state = Running
     np = 2
     properties = hadoop,collectl,ecryptid1,ecryptid2,ecryptid3
     ntype = cluster
     status = rectime=1465481907,macaddr=aa:01:00:80:0a:01,cpuclock=Fixed,varattr=,jobs=,state=free,size=11177112kb:11218120kb,netload=153921614917,gres=,loadave=0.09,ncpus=2,physmem=4047312kb,availmem=12207780kb,totmem=12435916kb,idletime=6571,nusers=3,nsessions=3,sessions=14437 18367 32268,uname=Linux node2801.banette.os 3.10.0-327.4.5.el7.ug.1.x86_64 #1 SMP Wed Jan 27 11:28:29 CET 2016 x86_64,opsys=linux
     mom_service_port = 15002
     mom_manager_port = 15003
     total_sockets = 1
     total_numa_nodes = 1
     total_cores = 2
     total_threads = 2
     dedicated_sockets = 0
     dedicated_numa_nodes = 0
     dedicated_cores = 0
     dedicated_threads = 0
~~~~

So, imho, the req_information.memory.0 should not be 8251038kb, but rather the physmem value so moab can actually start the job on the node. 

- branch 6.0-dev
- commit 5e082b7

Kind regards,
-- Andy

**Comment by itkovian** [comment]
I also noticed this occurs when submitting to a server where legacy_vmem=False.

~~~~
[root@master23 ~]# qstat -f 308
Job Id: 308.master23.banette.gent.vsc
    Job_Name = test_cgroups_tasks_and_memory_limit.sh
    Job_Owner = vsc40075@gligar01.gligar.gent.vsc
    job_state = Q
    queue = short
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Fri Jun 10 10:57:03 2016
    Error_Path = gligar01.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gent
	/vsc400/vsc40075/vsc-testing/torque/test_cgroups_tasks_and_memory_limi
	t.sh.e308
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = n
    mtime = Fri Jun 10 10:57:03 2016
    Output_Path = gligar01.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gen
	t/vsc400/vsc40075/vsc-testing/torque/test_cgroups_tasks_and_memory_lim
	it.sh.o308
    Priority = 0
    qtime = Fri Jun 10 10:57:03 2016
    Rerunable = True
    Resource_List.neednodes = 2:ppn=2
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 6gb
    Resource_List.walltime = 01:00:00
    substate = 10
    Variable_List = PBS_O_QUEUE=default,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,
	PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/v
	sc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/loc
	al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin,
	PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vs
	c-testing/torque,PBS_O_HOST=gligar01.gligar.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40075
    egroup = vsc40075
    queue_rank = 14
    queue_type = E
    etime = Fri Jun 10 10:57:03 2016
    submit_args = -l nodes=2:ppn=2 -l walltime=1:00:00 -l vmem=6g test_cgroups
	_tasks_and_memory_limit.sh
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = gligar01.gligar.gent.vsc
    request_version = 1
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.memory.0 = 6291456kb
    req_information.swap.0 = 6291456kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
~~~~

I would have expected this job to actually get scheduled, since setting legacy_vmem to False means I would ask for 3g per node, right? But `req_information.memory.0 = 6291456kb`, so I am assuming this job gets held for the same reason.

~~~~
[root@master23 ~]# tracejob 308
/var/spool/pbs/mom_logs/20160610: No such file or directory
/var/spool/pbs/sched_logs/20160610: No such file or directory

Job: 308.master23.banette.gent.vsc

06/10/2016 10:57:03.993 S    enqueuing into default, state 1 hop 1
06/10/2016 10:57:03.995 S    dequeuing from default, state QUEUED
06/10/2016 10:57:03.995 S    enqueuing into short, state 1 hop 1
06/10/2016 10:57:03  A    queue=default
06/10/2016 10:57:03  A    queue=short
06/10/2016 10:57:13.056 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/10/2016 10:57:44.094 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/10/2016 10:57:44.095 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/10/2016 10:58:15.055 S    Could not locate requested resources 'node2801.banette.gent.vsc:ppn=2+node2802.banette.gent.vsc:ppn=2' (node_spec failed)
06/10/2016 10:58:15.055 S    Job Modified at request of root@master23.banette.gent.vsc
~~~~

**Comment by dbeer** [comment]
The vmem request is not playing a role here: pbs_server doesn't check available memory when running a job. That is only enforced by Moab. Something else about the nodes is causing the failure. You sent in the pbsnodes output for node2801, but you didn't include the output for node2802. Do you have the details for its state at the time of the failure?

**Comment by stdweird** [comment]
@dbeer this also happens with a single node job, output below

```
[root@master23 ~]# qstat -f
Job Id: 319.master23.banette.gent.vsc
    Job_Name = testtest_COM
    Job_Owner = vsc40002@gligar03.gligar.gent.vsc
    job_state = Q
    queue = debug
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Wed Jun 15 19:14:01 2016
    Error_Path = gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gent
	/vsc400/vsc40002/testtest_COM.e319
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = be
    mtime = Wed Jun 15 19:15:04 2016
    Output_Path = gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gen
	t/vsc400/vsc40002/testtest_COM.o319
    Priority = 0
    qtime = Wed Jun 15 19:14:01 2016
    Rerunable = True
    Resource_List.neednodes = 1:ppn=1
    Resource_List.nice = 0
    Resource_List.nodect = 1
    Resource_List.nodes = 1:ppn=1
    Resource_List.vmem = 4224531456b
    Resource_List.walltime = 00:10:00
    substate = 10
    Variable_List = PBS_O_QUEUE=debug,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40002,PBS_O_LOGNAME=vsc40002,
	PBS_O_PATH=/user/data/gent/gvo000/gvo00002/JUBE/bin:/usr/local/bin:/b
	in:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin,
	PBS_O_MAIL=/var/spool/mail/vsc40002,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40002,
	PBS_O_HOST=gligar03.gligar.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40002
    egroup = vsc40002
    queue_rank = 1
    queue_type = E
    comment = cannot start job 319 - RM failure, rc: 15046,
	 msg: 'Resource temporarily unavailable'
    etime = Wed Jun 15 19:14:01 2016
    submit_args = s.sh
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = gligar03.gligar.gent.vsc
    request_version = 1
    req_information.task_count.0 = 1
    req_information.lprocs.0 = 1
    req_information.memory.0 = 4125519kb
    req_information.swap.0 = 4125519kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=1
```
```
[root@master23 ~]# pbsnodes  node2801.banette.gent.vsc
node2801.banette.gent.vsc
     state = free
     power_state = Running
     np = 2
     properties = hadoop,collectl,ecryptid1,ecryptid2,ecryptid3
     ntype = cluster
     status = rectime=1466011070,macaddr=aa:01:00:80:0a:01,cpuclock=Fixed,varattr=,jobs=,state=free,size=11177108kb:11218120kb,netload=171147573879,gres=,loadave=0.13,ncpus=2,physmem=4047312kb,availmem=12160296kb,totmem=12435916kb,idletime=62,nusers=2,nsessions=2,sessions=10759 28298,uname=Linux node2801.banette.os 3.10.0-327.4.5.el7.ug.1.x86_64 #1 SMP Wed Jan 27 11:28:29 CET 2016 x86_64,opsys=linux
     mom_service_port = 15002
     mom_manager_port = 15003
     total_sockets = 1
     total_numa_nodes = 1
     total_cores = 2
     total_threads = 2
     dedicated_sockets = 0
     dedicated_numa_nodes = 0
     dedicated_cores = 0
     dedicated_threads = 0
```
```
[root@master23 ~]# tracejob 319
/var/spool/pbs/mom_logs/20160615: No such file or directory
/var/spool/pbs/sched_logs/20160615: No such file or directory

Job: 319.master23.banette.gent.vsc

06/15/2016 19:14:01.751 S    enqueuing into debug, state 1 hop 1
06/15/2016 19:14:01  A    queue=debug
06/15/2016 19:14:02.072 S    Could not locate requested resources 'node2801.banette.gent.vsc' (node_spec failed) 
06/15/2016 19:14:33.138 S    Could not locate requested resources 'node2801.banette.gent.vsc' (node_spec failed) 
06/15/2016 19:14:33.140 S    Could not locate requested resources 'node2801.banette.gent.vsc' (node_spec failed) 
06/15/2016 19:15:04.100 S    Could not locate requested resources 'node2801.banette.gent.vsc' (node_spec failed) 
06/15/2016 19:15:04.101 S    Job Modified at request of root@master23.banette.gent.vsc
```

**Comment by stdweird** [comment]
bumped loglevel to 8, nothing to see on node2801 while this is attempted.

for a new job (same script, only specifying `vmem=1gb`, we immediately get
```
06/15/2016 19:24:41.881 S    enqueuing into debug, state 1 hop 1
06/15/2016 19:24:41  A    queue=debug
06/15/2016 19:25:06.080 S    Job Run at request of root@master23.banette.gent.vsc
06/15/2016 19:25:09.382 S    child reported success for job after 3 seconds (dest=???), rc=0
06/15/2016 19:25:09  A    user=vsc40002 group=vsc40002 jobname=testtest_COM queue=debug ctime=1466011481 qtime=1466011481 etime=1466011481
                          start=1466011509 owner=vsc40002@gligar03.gligar.gent.vsc exec_host=node2801.banette.gent.vsc/0
                          Resource_List.neednodes=1:ppn=1 Resource_List.nice=0 Resource_List.nodect=1 Resource_List.nodes=1:ppn=1
                          Resource_List.vmem=1gb Resource_List.walltime=00:10:00 
```

(and what pbsnodes reports about node2801 is correct wrt mem/vmem)

**Comment by stdweird** [comment]
@dbeer and to make it complete, specifying the `mem` gives
```
[root@master23 ~]# qstat -f 322|grep -C 2 mem
    qtime = Wed Jun 15 19:40:22 2016
    Rerunable = True
    Resource_List.mem = 3700mb
    Resource_List.neednodes = 1:ppn=1
    Resource_List.nice = 0
    Resource_List.nodect = 1
    Resource_List.nodes = 1:ppn=1
    Resource_List.vmem = 4224531456b
    Resource_List.walltime = 00:10:00
    substate = 10
--
    queue_type = E
    etime = Wed Jun 15 19:40:22 2016
    submit_args = s.sh -l mem=3700mb
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
--
    req_information.task_count.0 = 1
    req_information.lprocs.0 = 1
    req_information.memory.0 = 4125519kb
    req_information.swap.0 = 4125519kb
    req_information.thread_usage_policy.0 = allowthreads
```
seems like setting mem has no impact for `req_information.memory.0`

**Comment by dbeer** [comment]
Thanks for your help. Ken has been able to reproduce this locally and we should have a fix soon.

**Comment by itkovian** [comment]
Maybe we should provide our build options next time to make this easier for you to reproduce.

**Comment by knielson** [comment]
A fix for these has been checked in
ba55c56..6b52b53 6.0-dev -> 6.0-dev
e1ce92d..cb11034 develop -> develop

**Comment by itkovian** [comment]
Thanks.

**Comment by itkovian** [comment]
I am seeing now:

~~~~
    Resource_List.neednodes = 1:ppn=2
    Resource_List.nice = 0
    Resource_List.nodect = 1
    Resource_List.nodes = 1:ppn=2
    Resource_List.vmem = 8gb
    Resource_List.walltime = 48:00:00
~~~~

~~~~
    request_version = 1
    req_information.task_count.0 = 1
    req_information.lprocs.0 = 2
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
    req_information.task_usage.0.task.0.cpu_list = 0-1
    req_information.task_usage.0.task.0.mem_list = 0
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 2
    req_information.task_usage.0.task.0.host = node2801.banette.gent.vsc
    cpuset_string = node2801.banette.gent.vsc:0-1
    memset_string = node2801.banette.gent.vsc:0
~~~~

And the job started when requesting vmem=8g on a node with 4g physical memory, while the cgroup limits are set like this:

~~~~
vsc40075@node2801 (banette) ~> cat /sys/fs/cgroup/memory/torque/339.master23.banette.gent.vsc/memory.memsw.limit_in_bytes
9223372036854775807
vsc40075@node2801 (banette) ~> cat /sys/fs/cgroup/memory/torque/339.master23.banette.gent.vsc/memory.limit_in_bytes
8589934592
~~~~

So the first one is still wrong, imho, see also #372.

**Comment by knielson** [comment]
Try again. Swap not getting set corrected with the following two commits.
24827b8..633f117 6.0-dev -> 6.0-dev
f3bef4a..bf75d4e  develop -> develop

**Comment by itkovian** [comment]
I'm afraid it's not fixed.

~~~~
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.kmem.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.kmem.tcp.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.limit_in_bytes:1610612736
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.memsw.limit_in_bytes:9223372036854775807
/sys/fs/cgroup/memory/torque/352.master23.banette.gent.vsc/memory.soft_limit_in_bytes:9223372036854775807
~~~~

Are you guys actually able to reproduce this?

**Comment by itkovian** [comment]
I have a regression on this issue:

qstat -f output
~~~~
oot@master23 ~]# qstat -f 359
Job Id: 359.master23.banette.gent.vsc
    Job_Name = STDIN
    Job_Owner = vsc40075@gligar03.gligar.gent.vsc
    job_state = Q
    queue = short
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Tue Jun 21 20:02:42 2016
    Error_Path = gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gent
	/vsc400/vsc40075/vsc-testing/torque/STDIN.e359
    Hold_Types = n
    interactive = True
    Join_Path = n
    Keep_Files = n
    Mail_Points = n
    mtime = Tue Jun 21 20:02:42 2016
    Output_Path = gligar03.gligar.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gen
	t/vsc400/vsc40075/vsc-testing/torque/STDIN.o359
    Priority = 0
    qtime = Tue Jun 21 20:02:42 2016
    Rerunable = False
    Resource_List.neednodes = 1:ppn=2
    Resource_List.nice = 0
    Resource_List.nodect = 1
    Resource_List.nodes = 1:ppn=2
    Resource_List.vmem = 8gb
    Resource_List.walltime = 00:10:00
    substate = 10
    Variable_List = PBS_O_QUEUE=default,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,
	PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/v
	sc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/loc
	al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin,
	PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vs
	c-testing/torque,PBS_O_HOST=gligar03.gligar.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40075
    egroup = vsc40075
    queue_rank = 14
    queue_type = E
    etime = Tue Jun 21 20:02:42 2016
    submit_args = -l nodes=1:ppn=2 -l vmem=8g -l walltime=10:00 -I
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = gligar03.gligar.gent.vsc
    request_version = 1
    req_information.task_count.0 = 1
    req_information.lprocs.0 = 2
    req_information.memory.0 = 8388608kb
    req_information.swap.0 = 8388608kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
~~~~


So jobs are once more not starting if I specify more vmem then physical RAM in the node (note that the req_information.memory.0 is back and the same as the swap value.

I was running 6.0-dev, commit 332175e.

**Comment by knielson** [comment]
Andy,

Rick got me onto your system but I did not see cgroups installed on the MOM in the reservation. I may not be clear on the configuration of your cluster. I would like to get on the phone with you and walk through this. You can e-mail me directly at knielson@adaptivecomputing.com

I have run more tests on my end and with the syntax you gave in the job script things are working for me. We need to figure out what is different between us.

Thanks

Ken

**Comment by itkovian** [comment]
I still see the wrong values here, also with #378.

~~~~
[root@master23 ~]# qstat -f 391
Job Id: 391.master23.banette.gent.vsc
    Job_Name = test_cgroups_tasks_and_memory_limit.sh
    Job_Owner = vsc40075@node2804.banette.gent.vsc
    job_state = Q
    queue = short
    server = master23.banette.gent.vsc
    Checkpoint = u
    ctime = Fri Jun 24 13:03:53 2016
    Error_Path = node2804.banette.gent.vsc:/vscmnt/gent_vulpix/_/user/home/gen
	t/vsc400/vsc40075/vsc-testing/torque/test_cgroups_tasks_and_memory_lim
	it.sh.e391
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = n
    mtime = Fri Jun 24 13:03:53 2016
    Output_Path = node2804.banette.gent.vsc:/vscmnt/gent_vulpix/_/user/home/ge
	nt/vsc400/vsc40075/vsc-testing/torque/test_cgroups_tasks_and_memory_li
	mit.sh.o391
    Priority = 0
    qtime = Fri Jun 24 13:03:53 2016
    Rerunable = True
    Resource_List.neednodes = 2:ppn=2
    Resource_List.nice = 0
    Resource_List.nodect = 2
    Resource_List.nodes = 2:ppn=2
    Resource_List.vmem = 5gb
    Resource_List.walltime = 00:30:00
    substate = 10
    Variable_List = PBS_O_QUEUE=default,
	PBS_O_HOME=/user/home/gent/vsc400/vsc40075,PBS_O_LOGNAME=vsc40075,
	PBS_O_PATH=/user/data/gent/vsc400/vsc40075/JUBE/bin:/user/home/gent/v
	sc400/vsc40075/.cabal/bin:/user/home/gent/vsc400/vsc40075/bin:/usr/loc
	al/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin,
	PBS_O_MAIL=/var/spool/mail/vsc40075,PBS_O_SHELL=/bin/bash,
	PBS_O_LANG=en_US.UTF-8,PBS_O_SUBMIT_FILTER=/usr/bin/submitfilter,
	PBS_O_WORKDIR=/vscmnt/gent_vulpix/_/user/home/gent/vsc400/vsc40075/vs
	c-testing/torque,PBS_O_HOST=node2804.banette.gent.vsc,
	PBS_O_SERVER=master23.banette.gent.vsc
    euser = vsc40075
    egroup = vsc40075
    queue_rank = 4
    queue_type = E
    etime = Fri Jun 24 13:03:53 2016
    submit_args = -l walltime=30:00 -l nodes=2:ppn=2 -l vmem=5g test_cgroups_t
	asks_and_memory_limit.sh
    checkpoint_dir = /export/home/checkpoints
    fault_tolerant = False
    job_radix = 0
    submit_host = node2804.banette.gent.vsc
    request_version = 1
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.memory.0 = 5242880kb
    req_information.swap.0 = 5242880kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
~~~~

I requested vmem=5g, which is clearly reflected in the req_information structure. This means this job will never start. The expected value would have been physical memory for the req_information.memory.0 setting, thereby also setting memory.limit_in_bytes to this values, whereas memory.memsw.limit_in_bytes can stay at the larger value of 5g.

**Comment by itkovian** [comment]
I can confirm that under 56698fb, this seems to be resolved again.

~~~~
    req_information.task_count.0 = 2
    req_information.lprocs.0 = 2
    req_information.swap.0 = 8388608kb
    req_information.thread_usage_policy.0 = allowthreads
    req_information.hostlist.0 = node2801.banette.gent.vsc:ppn=2
    req_information.hostlist.0 = node2802.banette.gent.vsc:ppn=2
    req_information.task_usage.0.task.0.cpu_list = 0-1
    req_information.task_usage.0.task.0.mem_list = 0
    req_information.task_usage.0.task.0.cores = 0
    req_information.task_usage.0.task.0.threads = 2
    req_information.task_usage.0.task.0.host = node2801.banette.gent.vsc
    req_information.task_usage.0.task.1.cpu_list = 0-1
    req_information.task_usage.0.task.1.mem_list = 0
    req_information.task_usage.0.task.1.cores = 0
    req_information.task_usage.0.task.1.threads = 2
    req_information.task_usage.0.task.1.host = node2802.banette.gent.vsc
~~~~

and 

~~~~
memory.limit_in_bytes: 4144447488
memory.memsw.limit_in_bytes: 8589934592
~~~~
